-- sales_report.sql

/**
 * 
 * @author Alonso Peralta Espinoza
 *
 * Generates a sales report summarizing item quantities sold and total revenue within a date range.
 *
 * @description
 * - Aggregates sales data to provide total quantities sold and total revenue for each menu item.
 *
 * @columns
 * - `item_name`: Name of the menu item.
 * - `total_sold`: Total number of units sold for the menu item.
 * - `total_revenue`: Total revenue generated by the menu item.
 *
 * @parameters
 * - `$1`: Start date for the sales data (inclusive).
 * - `$2`: End date for the sales data (inclusive).
 *
 * @grouping
 * - Groups results by `item_name` to calculate totals for each menu item.
 *
 * @order
 * - Results are ordered by `total_sold` in descending order.
 *
 * @usage
 * - Used for analyzing sales performance and identifying top-selling items.
 */

SELECT 
    m.name AS item_name,
    COUNT(sm.menu_item_id) AS total_sold,
    SUM(s.price) AS total_revenue
FROM 
    sales s
JOIN 
    sales_menu sm ON s.sale_number = sm.sale_number
JOIN 
    menu m ON sm.menu_item_id = m.menu_item_id
WHERE 
    s.date_of_sale BETWEEN $1 AND $2
GROUP BY 
    m.name
ORDER BY 
    total_sold DESC;