export const textArray = [
  "We Wok For You",
  "Tap to Order Now",
  "A La Carte",
  "Select:",
  "Any Item",
  "Any Drink",
  "Side",
  "Sides",
  "Entrees",
  "Extras",
  "Back to Menu",
  "Done",
  "Plate",
  "Bigger Plate",
  "1 Side",
  "1 Entree",
  "2 Entree",
  "2 Entrees",
  "3 Entree",
  "3 Entrees",
  "Back to Menu",
  "Back to Sides",
  "Bowl",
  "Start Over",
  "Place Order",
  "Subtotal:",
  "Tax:",
  "Total |",
  "Choose A Meal Above",
  "Select Items",
  "Super Greens",
  "Select Sides",
  "Select Entrees",
  "Checkout",
  "Start Over",
  "Bowl | $9.50",
  "Plate | $11.50",
  "Bigger Plate | $13.50",
  "Orange Chicken",
  "Honey Walnut Shrimp",
  "Grilled Teriyaki Chicken",
  "Broccoli Beef",
  "Kung Pao Chicken",
  "Black Pepper Sirloin Steak",
  "Honey Sesame Chicken",
  "Beijing Beef",
  "Mushroom Chicken",
  "SweetFire Chicken",
  "String Bean Chicken",
  "Black Pepper Chicken",
  "Super Greens",
  "Chow Mein",
  "Fried Rice",
  "White Steamed Rice",
  "Fountain Drink",
  "Bottle Drink",
  "Chicken Egg Roll",
  "Veggie Spring Roll",
  "Cream Cheese Rangoon",
  "Apple Pie Roll",
  "Calories",
  "Designation:",
  "Our signature dish. Crispy chicken wok-tossed in a sweet and spicy orange sauce.",
  "Large tempura-battered shrimp, wok-tossed in a honey sauce and topped with glazed walnuts.",
  "Grilled chicken hand-sliced to order and served with teriyaki sauce.",
  "A classic favorite. Tender beef and fresh broccoli in a ginger soy sauce.",
  "A Sichuan-inspired dish with chicken, peanuts and vegetables, finished with chili peppers.",
  "Sirloin steak wok-seared with baby broccoli, onions, red bell peppers, and mushrooms in a savory black pepper sauce.",
  "Crispy strips of white-meat chicken with veggies in a mildly sweet sauce with organic honey.",
  "Crispy beef, bell peppers anf onions in a sweet-tangy sauce.",
  "A delicate combination of chicken, mushrooms and zucchini wok-tossed with a light ginger soy sauce.",
  "Crispy boneless chicken bites and veggies wok-tossed in an extry spicy sauce.",
  "Chicken breast, string beans and onions wok-tossed in a mild ginger soy sauce.",
  "Marinated chicken, celery and onions in a bold black pepper sauce.",
  "A healthful medley of broccoli, kale, and cabbage.",
  "Stir-fried wheat noodles with onions, celery, and cabbage.",
  "Prepared steamed white rice with soy sauce, eggs, peas, carrots, and green onions.",
  "Prepared steamed white rice.",
  "A fresh Beverage of any choice (calories may vary).",
  "A bottle of water given any choice.",
  "Cabbage, carrots, green onions and chicken in a crispy wonton wrapper.",
  "Cabbage, carrots, green onions and Chinese noodles in a crispy wonton wrapper.",
  "Wonton wrappers filled with cream cheese and served with sweet and sour sauce.",
  "Jucy apples and fall spices in a crispy rolled pastry, finished with cinnamon sugar.",
  "Spicy",
  "Premium",
  "None",
  "Veggie",
  "No specific designation",
  "Close",
  "Don't forget to add sauce",
  "Soy Sauce",
  "Sweet & Sour Sauce",
  "Chili Sauce",
  "Teriyaki Sauce",
  "Hot Mustard",
  "Any Food Item",
  "BOWL",
  "PLATE",
  "BIGGER PLATE",
  "A LA CARTE",
  "Loading recommended item...",
  "Item not found in the menu.",
  "This month's hot item",
  "Calories: ",
  " Designation: ",
  "Testing Rolls",
  "Switch Theme",
  "Current Theme:",
  "Adjust Font Size",
  "Current Size:",
  "Low Vision Theme",
  "Your order is",
  "on its way!",
  "Order Number",
  "Customer Login",
  "You have",
  "points! Would you like to use 1000 points for a 10% discount?",
  "Use 1000 points for 10% off",
  "Sign Up",
  "Submit",
  "Customer Points",
  "Cancel",
  "Customer Sign Up",
  "Phone Number:",
  "Name:",
  "Date of Birth (optional):",
];
