
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (1, 'Chow Mein', 'food item', 'Noodles, Stir-fry-veggies, oil, seasoning', 1002, 1195, 3473);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (2, 'Fried Rice', 'food item', 'Rice, oil, seasoning, egg, rice-veggies', 614, 1524, 2510);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (3, 'White Steamed Rice', 'food item', 'Rice', 401, 1733, 2413);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (4, 'Super Greens', 'food item', 'assorted greens', 206, 1504, 2538);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (5, 'Orange Chicken', 'food item', 'Cut-Chicken, orange-sauce', 1500, 1730, 3883);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (6, 'Black Pepper Sirloin Steak', 'food item', 'Sirloin Steak, black-pepper-sauce, black-pepper-veggies', 921, 1171, 3014);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (7, 'Honey Walnut Shrimp', 'food item', 'Shrimp, honey-walnut-veggies, honey-walnut-sauce', 317, 1969, 3711);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (8, 'Grilled Teriyaki Chicken', 'food item', 'Chicken Breast, teriyaki-sauce', 373, 1503, 3614);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (9, 'Kung Pao Chicken', 'food item', 'Cut-Chicken, kung-pao-sauce, kung-pao-veggies', 1301, 1093, 3064);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (10, 'Honey Sesame Chicken Breast', 'food item', 'Chicken Breast, sesame-veggies, honey-sesame-sauce', 1537, 1187, 3063);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (11, 'Beijing Beef', 'food item', 'Beef, beijing-veggies, beijing-sauce', 1188, 1251, 3500);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (12, 'Mushroom Chicken', 'food item', 'Cut-Chicken, mushroom-veggies, mushroom-sauce', 892, 1227, 2698);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (13, 'SweetFire Chicken Breast', 'food item', 'Chicken Breast, sweetFire-veggies, sweetfire-sauce', 27, 1130, 2707);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (14, 'String Bean Chicken Breast', 'food item', 'Chicken Breast, string-bean-veggies, mushroom-sauce', 441, 1593, 2481);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (15, 'Broccoli Beef', 'food item', 'Beef, assorted greens, broccoli-sauce', 421, 1070, 2846);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (16, 'Black Pepper Chicken', 'food item', 'Cut-Chicken, black-pepper-veggies, black-pepper-sauce', 1272, 1206, 2231);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (17, 'Chicken Egg Roll', 'food item', 'pastry-wrapper, oil, chicken-egg-filling', 1709, 1690, 3638);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (18, 'Veggie Spring Roll', 'food item', 'pastry-wrapper, veggie-filling, oil', 1076, 1977, 2693);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (19, 'Cream Cheese Rangoon', 'food item', 'pastry-wrapper, oil, cream-cheese-filling', 277, 1151, 2744);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (20, 'Apple Pie Roll', 'food item', 'pastry-wrapper, apple-pie-filling, oil', 877, 1026, 2251);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (21, 'Dr Pepper', 'fountain drink', NULL, 3758, 3851, 4701);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (22, 'Coca Cola', 'fountain drink', NULL, 1754, 2935, 4886);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (23, 'Diet Coke', 'fountain drink', NULL, 3111, 3875, 4424);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (24, 'Barq Root Beer', 'fountain drink', NULL, 3987, 2701, 5788);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (25, 'Fanta Orange', 'fountain drink', NULL, 140, 3384, 4955);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (26, 'Minute Maid Lemonade', 'fountain drink', NULL, 2273, 3391, 4383);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (27, 'Powerade Berry Blast', 'fountain drink', NULL, 3644, 2153, 5434);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (28, 'Sprite', 'fountain drink', NULL, 3340, 2847, 5509);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (29, 'Powerade Punch', 'bottled drink', NULL, 177, 367, 649);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (30, 'Bottled Water', 'bottled drink', NULL, 291, 498, 934);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (31, 'Minute Maid Apple Juice', 'bottled drink', NULL, 324, 408, 989);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (32, 'Coke Mexico', 'bottled drink', NULL, 324, 343, 785);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (33, 'Bai Coco Fusion', 'bottled drink', NULL, 34, 394, 891);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (34, 'Bowl-box', 'supply item', NULL, 9240, 8534, 11349);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (35, 'Plate-box', 'supply item', NULL, 6620, 8164, 12753);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (36, 'Bigger-Plate-box', 'supply item', NULL, 213, 8923, 13639);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (37, 'A-La-Carte-carton', 'supply item', NULL, 7163, 9491, 13670);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (38, 'Drink-Cups', 'supply item', NULL, 2965, 9640, 12076);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (39, 'utensil-packs', 'supply item', NULL, 1565, 8591, 11683);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (40, 'straws', 'supply item', NULL, 3076, 8460, 10090);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (41, 'bags', 'supply item', NULL, 6920, 8267, 13161);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (42, 'Noodles', 'ingredient', NULL, 1002, 2431, 4080);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (43, 'Rice', 'ingredient', NULL, 1015, 2278, 4162);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (44, 'Chicken Beast', 'ingredient', NULL, 2378, 2049, 4737);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (45, 'Cut-Chicken', 'ingredient', NULL, 4965, 2867, 4015);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (46, 'Beef', 'ingredient', NULL, 1609, 2141, 4779);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (47, 'Sirloin Steak', 'ingredient', NULL, 921, 2524, 4855);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (48, 'Shrimp', 'ingredient', NULL, 317, 2879, 4267);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (49, 'Stir-fry-veggies', 'ingredient', NULL, 1002, 2760, 4297);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (50, 'rice-veggies', 'ingredient', NULL, 614, 2141, 4418);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (51, 'assorted greens', 'ingredient', NULL, 627, 2736, 4860);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (52, 'black-pepper-veggies', 'ingredient', NULL, 2193, 2930, 4493);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (53, 'honey-walnut-veggies', 'ingredient', NULL, 317, 2835, 4229);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (54, 'mushroom-veggies', 'ingredient', NULL, 892, 2011, 4303);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (55, 'sweetFire-veggies', 'ingredient', NULL, 27, 2454, 4996);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (56, 'string-bean-veggies', 'ingredient', NULL, 441, 2160, 4736);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (57, 'beijing-veggies', 'ingredient', NULL, 1188, 2316, 4347);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (58, 'sesame-veggies', 'ingredient', NULL, 1537, 2144, 4432);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (59, 'kung-pao-veggies', 'ingredient', NULL, 1301, 2268, 4405);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (60, 'pastry-wrapper', 'ingredient', NULL, 3939, 2561, 4842);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (61, 'veggie-filling', 'ingredient', NULL, 1076, 2826, 4993);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (62, 'chicken-egg-filling', 'ingredient', NULL, 1709, 2002, 4425);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (63, 'cream-cheese-filling', 'ingredient', NULL, 277, 2192, 4257);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (64, 'apple-pie-filling', 'ingredient', NULL, 877, 2763, 4886);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (65, 'orange-sauce', 'ingredient', NULL, 1500, 2163, 4629);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (66, 'black-pepper-sauce', 'ingredient', NULL, 2193, 2875, 4918);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (67, 'teriyaki-sauce', 'ingredient', NULL, 373, 2694, 4440);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (68, 'honey-walnut-sauce', 'ingredient', NULL, 317, 2717, 4763);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (69, 'broccoli-sauce', 'ingredient', NULL, 421, 2313, 4301);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (70, 'beijing-sauce', 'ingredient', NULL, 1188, 2501, 4142);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (71, 'honey-sesame-sauce', 'ingredient', NULL, 1537, 2288, 4282);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (72, 'kung-pao-sauce', 'ingredient', NULL, 1301, 2243, 4949);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (73, 'mushroom-sauce', 'ingredient', NULL, 1333, 2773, 4905);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (74, 'sweetfire-sauce', 'ingredient', NULL, 27, 2126, 4036);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (75, 'string-bean-sauce', 'ingredient', NULL, 0, 2690, 4572);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (76, 'oil', 'ingredient', NULL, 5555, 2979, 4939);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (77, 'seasoning', 'ingredient', NULL, 1616, 2339, 4643);
INSERT INTO inventory (inventory_id, item_name, item_type, ingredients, curr_amount, needed4Week, needed4GameWeek) VALUES (78, 'egg', 'ingredient', NULL, 614, 2703, 4316);
