DELETE FROM menu WHERE name = 'Sugar Chicken';

INSERT INTO menu (menu_item_id, name, calories, price, description, tags, image)
VALUES
    (1, 'Bowl', 510, 8.3, 'One entrée item and one side item.', 'None', NULL),
    (2, 'Plate', 750, 9.8, 'Two entrée items and one side item.', 'None', NULL),
    (3, 'Bigger Plate', 1050, 11.5, 'Three entrée items and one side item.', 'None', NULL),
    (4, 'A La Carte', 0, 0, 'Single entrée or side item.', 'None', NULL),
    (5, 'Bottle Drink', 0, 2, 'A bottle of water given any choice.', 'None', NULL),
    (6, 'Fountain Drink', 360, 2.3, 'A fresh beverage of any choice (calories may vary).', 'None', NULL),
    (7, 'Dumplings', 190, 1.99, 'Seasonal dumplings with a variety of fillings.', 'Seasonal', NULL),
    (8, 'Orange Chicken', 510, 8.5, 'Our signature dish. Crispy chicken wok-tossed in a sweet and spicy orange sauce.', 'Spicy', 'Chicken_OrangeChicken.png'),
    (9, 'Honey Walnut Shrimp', 430, 8.5, 'Large tempura-battered shrimp, wok-tossed in a honey sauce and topped with glazed walnuts.', 'Premium', 'Seafood_HoneyWalnutShrimp.png'),
    (10, 'Grilled Teriyaki Chicken', 275, 8.5, 'Grilled chicken hand-sliced to order and served with teriyaki sauce.', 'None', 'Chicken_GrilledTeriyakiChicken.png'),
    (11, 'Broccoli Beef', 150, 8.5, 'A classic favorite. Tender beef and fresh broccoli in a ginger soy sauce.', 'None', 'Beef_BroccoliBeef.png'),
    (12, 'Kung Pao Chicken', 320, 8.5, 'A Sichuan-inspired dish with chicken, peanuts and vegetables, finished with chili peppers.', 'Spicy', 'Chicken_KungPaoChicken.png'),
    (13, 'Black Pepper Sirloin Steak', 180, 8.5, 'Sirloin steak wok-seared with baby broccoli, onions, red bell peppers, and mushrooms in a savory black pepper sauce.', 'Premium', 'Beef_ShanghaiAngusSteak.png'),
    (14, 'Honey Sesame Chicken', 340, 8.5, 'Crispy strips of white-meat chicken with veggies in a mildly sweet sauce with organic honey.', 'None', 'ChickenBreast_HoneySesameChickenBreast.png'),
    (15, 'Beijing Beef', 480, 8.5, 'Crispy beef, bell peppers and onions in a sweet-tangy sauce.', 'Spicy', 'Beef_BeijingBeef.png'),
    (16, 'Mushroom Chicken', 220, 8.5, 'A delicate combination of chicken, mushrooms and zucchini wok-tossed with a light ginger soy sauce.', 'None', 'Chicken_MushroomChicken.png'),
    (17, 'SweetFire Chicken', 400, 8.5, 'Crispy boneless chicken bites and veggies wok-tossed in an extra spicy sauce.', 'Spicy', 'Chicken_SweetFire.png'),
    (18, 'String Bean Chicken', 210, 8.5, 'Chicken breast, string beans, and onions wok-tossed in a mild ginger soy sauce.', 'None', 'ChickenBreast_StringBeanChickenBreast.png'),
    (19, 'Black Pepper Chicken', 280, 8.5, 'Marinated chicken, celery and onions in a bold black pepper sauce.', 'None', 'Chicken_BlackPepperChicken.png'),
    (20, 'Super Greens', 130, 4.4, 'A healthful medley of broccoli, kale, and cabbage.', 'Veggie', 'Vegetables_SuperGreens.png'),
    (21, 'Chow Mein', 600, 4.4, 'Stir-fried wheat noodles with onions, celery, and cabbage.', 'Veggie', 'Sides_ChowMein.png'),
    (22, 'Fried Rice', 620, 4.4, 'Prepared steamed white rice with soy sauce, eggs, peas, carrots, and green onions.', 'Veggie', 'Sides_FriedRice.png'),
    (23, 'White Steamed Rice', 520, 4.4, 'Prepared steamed white rice.', 'Veggie', 'Sides_WhiteSteamedRice.png'),
    (24, 'Chicken Egg Roll', 200, 2, 'Cabbage, carrots, green onions, and chicken in a crispy wonton wrapper.', 'None', NULL),
    (25, 'Veggie Spring Roll', 240, 2, 'Cabbage, carrots, green onions, and Chinese noodles in a crispy wonton wrapper.', 'Veggie', NULL),
    (26, 'Cream Cheese Rangoon', 190, 2, 'Wonton wrappers filled with cream cheese and served with sweet and sour sauce.', 'Veggie', NULL),
    (27, 'Apple Pie Roll', 150, 4, 'Juicy apples and fall spices in a crispy rolled pastry, finished with cinnamon sugar.', 'Veggie', NULL);